version: "3.8"

services:
  api:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./back:/app
    ports:
      - "9000:9000"
  client:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./front:/app
    ports:
      - "80:80"
    depends_on:
      - api
